#prod 服务器端读取数据  dev  本地读取数据
spring: 
  profiles: 
    #active: prod
    active: dev
#页面配置
  mvc:
    view:
      prefix: /
      suffix: .html
  datasource: 
    driver-class-name: oracle.jdbc.driver.OracleDriver
    name: gxpt
#正式环境 37
    url: jdbc:oracle:thin:@110.185.166.37:6565:GXPT
#测试环境 39
    #url: jdbc:oracle:thin:@10.176.155.39:1521:GXPT
    username: gxpt
    password: gxpt123GXPT
    type: com.zaxxer.hikari.HikariDataSource
#使用hikari数据源
    hikari:
    #此属性控制客户端（即您）等待池中连接的最大毫秒数
      connectionTimeout:  60000
    #此属性控制连接测试活动的最长时间
      validationTimeout:  30000
    #此属性控制允许池到达的最大大小，包括空闲和正在使用的连接。
      maximum-pool-size:  20 
    
  redis: 
      host: 10.176.155.250
      #redis密码，没有密码的可以用～表示
      password: ~
      port: 6379
      jedis: 
        pool:
          max-active: 100
          max-idle: 10
          max-wait: 100000
mybatis:
  type-aliases-package: com.lensyn.ispbs.service.mapper
  mapper-locations: classpath:mapper/*.xml
#服务启动端口
server :  
  port :  10229
#slf4j日志地址
logging :
  pattern :
    console : "%d- %msg%n"
  path : /home/isp/sh/jar/log/
